#DataBase Configuration
UserName: root
PassWord: 123456
Host: 127.0.0.1
Port: 3306
Dbname: test
Dsn: root:123456@tcp(localhost:3306)/ngrok?charset=utf8mb4&parseTime=True&loc=Local
MaxIdleConns: 10
MaxOpenConns: 100